### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by Antoni-Czaplicki** [BOLL7708/OpenVROverlayPipe#9]
Hi!
I would like to create an app that allows to connect SteamVR Headset with Home Assistant and I was wondering whether I could use code from your project for displaying notifications and as a base for communicating with openvr.

I've attached a few screenshots to show the preview of what i've achieved so far😇
<div class="flex-container">
<img src="https://github.com/BOLL7708/OpenVROverlayPipe/assets/56671347/decec5f7-1b14-409b-b1c9-e3b12c8525d4" alt="drawing" width="200"/>
<img src="https://github.com/BOLL7708/OpenVROverlayPipe/assets/56671347/4d09f8a3-253b-4c08-bba5-7e2ce876a367" alt="drawing" width="300"/>
<img src="https://github.com/BOLL7708/OpenVROverlayPipe/assets/56671347/f4510e72-a45e-48e3-8253-cb894de4bb4f" alt="drawing" width="200"/>
</div>

**Comment by BOLL7708** [comment]
Done! I went for AGPLv3, I hope that works out for you :)
